name: reviewdog
on:
  pull_request:
    paths:
      - '**/*.{js,jsx,ts,tsx}'
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - '.github/workflows/reviewdog.yml'

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: '--config eslint.config.mjs "apps/**/*.{ts,tsx}" "packages/**/*.{ts,tsx}"'